# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a737cc72edb4ff6ada5a95ad1011dd846a60d29378cc9a57bf0312ea74e86aff27cdc79a6b3fbafe97ac76aaa834ccafb10bf9a611be81912c378bff9aed758

test:
  secret_key_base: d71d9a2b136a6708e9de354fef49a8334627a6ed752c76adcace19922d0f41e60f2f11e3dfed8aca54ab1153335d2c6eb3b21d6df0ebedd49a7788727cb2125a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
